on: 
   workflow_dispatch:



jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout del código
       uses: actions/checkout@v3
        
     - name: llamar a la accion
       uses: ./.github/action
       with:
         status: online
         dia: jueves
